import { NavigationItem } from './shared/models/main.models';

export const navigationItems: NavigationItem[] = [
  {
    path: '/summary',
    icon: 'receipt_long',
    label: 'app.navigation.summary',
    hasPermission: true,
    order: 1,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
  {
    path: '/sales',
    icon: 'credit_card',
    label: 'app.navigation.sales',
    hasPermission: true,
    order: 2,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
  {
    path: '/receivables',
    icon: 'attach_money',
    label: 'app.navigation.receivables',
    hasPermission: true,
    order: 3,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
  {
    path: '/prepayments',
    icon: 'calendar_today',
    label: 'app.navigation.prepayments',
    hasPermission: true,
    order: 4,
    roles: ['Administrador', 'Comunicacao', 'Usuario', 'AD'],
  },
  {
    path: '/statements',
    icon: 'receipt',
    label: 'app.navigation.statements',
    hasPermission: true,
    order: 5,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
  {
    path: '/reports',
    icon: 'system_update_alt',
    label: 'app.navigation.reports',
    hasPermission: true,
    order: 6,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
  {
    icon: 'engineering',
    label: 'app.navigation.administration',
    hasPermission: true,
    order: 7,
    roles: ['Administrador', 'Marketing', 'AD'],
    children: [
      {
        path: '/communication',
        icon: '',
        label: 'app.navigation.communication',
        hasPermission: true,
        order: 1,
        roles: ['Administrador', 'Marketing', 'AD'],
      },
    ],
  },
  {
    path: '/rates-fees',
    icon: 'monetization_on',
    label: 'app.navigation.rates-fees',
    hasPermission: true,
    order: 9,
    roles: [
      'Administrador',
      'Comunicacao',
      'Usuario',
      'Marketing',
      'Default',
      'AD',
    ],
  },
];
